// Temporal Workflow contracts for Apps namespace
syntax = "proto3";

package acme.apps.domain.apps.v1;

import "google/protobuf/timestamp.proto";
import "acme/apps/domain/v1/values.proto";
import "acme/oms/v1/message.proto";
import "acme/oms/v1/values.proto";
import "acme/processing/domain/v1/workflows.proto";


// CompleteOrder

message CompleteOrderRequest {
  google.protobuf.Timestamp timestamp = 1;
  optional CompleteOrderRequestExecutionOptions options = 2;
  string order_id = 3;
  string customer_id = 4;
}

message CompleteOrderRequestExecutionOptions {
  optional int64 completion_timeout_secs = 1;
  optional int64 processing_timeout_secs = 2;
  optional acme.oms.v1.OmsProperties oms_properties = 3;
}

message GetCompleteOrderStateResponse {
  CompleteOrderRequest args = 1;
  CompleteOrderRequestExecutionOptions options = 2;
  repeated string errors = 3;
  repeated SubmitOrderRequest submitted_orders = 4;
  repeated CapturePaymentRequest captured_payments = 5;
  optional CancelOrderRequest cancellation = 6;
  optional acme.processing.domain.processing.v1.ProcessOrderRequest process_order = 7;
  optional acme.processing.domain.processing.v1.GetProcessOrderStateResponse processed_order = 8;
}

message GetOptionsRequest {
  google.protobuf.Timestamp timestamp = 1;
  optional CompleteOrderRequestExecutionOptions options = 2;
}

message CancelOrderRequest {
  google.protobuf.Timestamp timestamp = 1;
  string reason = 2;
  string cancelled_by = 3;
}

message CancelOrderResponse {

}

message SubmitOrderRequest {
  google.protobuf.Timestamp timestamp = 1;
  string order_id = 2;
  acme.oms.v1.Order order = 3;
  optional CompleteOrderRequest complete_order_request = 4;
}

message CapturePaymentRequest {
  google.protobuf.Timestamp timestamp = 1;
  string order_id = 2;
  acme.oms.v1.Payment payment = 3;
  optional CompleteOrderRequest complete_order_request = 4;
}