apiVersion: apps/v1
kind: Deployment
metadata:
  name: enablements-workers
  namespace: temporal-oms-enablements
  labels:
    app: enablements-workers
    component: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enablements-workers
  template:
    metadata:
      labels:
        app: enablements-workers
        component: worker
        version: "1.0.0"
      annotations:
        instrumentation.opentelemetry.io/inject-sdk: "true"
    spec:
      serviceAccountName: enablements-workers
      containers:
      - name: worker
        image: temporal-oms/enablements-workers:latest
        imagePullPolicy: Never
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: k8s
        - name: JAVA_OPTS
          value: "-Dgrpc.netty.keepaliveTime=30 -Dgrpc.netty.keepaliveTimeout=5 -Dgrpc.netty.keepaliveWithoutCalls=true"
        - name: ENABLEMENTS_DEPLOYMENT_MANIFEST_TEMPLATE
          value: /etc/config/k8s-templates/worker-deployment-template.yaml
        envFrom:
        - configMapRef:
            name: temporal-oms-config
        - secretRef:
            name: temporal-oms-secrets
        volumeMounts:
        - name: temporal-config
          mountPath: /etc/config/temporal
          readOnly: true
        - name: temporal-secret
          mountPath: /etc/config/temporal-secret
          readOnly: true
        - name: worker-deployment-template
          mountPath: /etc/config/k8s-templates
          readOnly: true
        resources:
          requests:
            memory: "384Mi"
            cpu: "200m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
      volumes:
      - name: temporal-config
        configMap:
          name: temporal-enablements-config
          defaultMode: 0444
      - name: temporal-secret
        secret:
          secretName: temporal-enablements-api-key
          defaultMode: 0444
      - name: worker-deployment-template
        configMap:
          name: worker-deployment-template
          defaultMode: 0444
