---
apiVersion: v1
kind: Namespace
metadata:
  name: temporal-oms-apps
  labels:
    name: temporal-oms-apps
    app: temporal-oms
    component: apps

---
apiVersion: v1
kind: Namespace
metadata:
  name: temporal-oms-processing
  labels:
    name: temporal-oms-processing
    app: temporal-oms
    component: processing

---
apiVersion: v1
kind: Namespace
metadata:
  name: temporal-oms-fulfillment
  labels:
    name: temporal-oms-fulfillment
    app: temporal-oms
    component: fulfillment

---
apiVersion: v1
kind: Namespace
metadata:
  name: temporal-oms-enablements
  labels:
    name: temporal-oms-enablements
    app: temporal-oms
    component: enablements

---
apiVersion: v1
kind: Namespace
metadata:
  name: temporal-oms-web
  labels:
    name: temporal-oms-web
    app: temporal-oms
    component: web
